// Mocks generated by Mockito 5.4.4 from annotations
// in court_booker_app/test/models/book_model.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:court_booker_app/models/book_model.dart' as _i3;
import 'package:court_booker_app/models/court_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCourtModel_1 extends _i1.SmartFake implements _i2.CourtModel {
  _FakeCourtModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookModel extends _i1.Mock implements _i3.BookModel {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  DateTime get dateTime => (super.noSuchMethod(
        Invocation.getter(#dateTime),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#dateTime),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#dateTime),
        ),
      ) as DateTime);

  @override
  _i2.CourtModel get court => (super.noSuchMethod(
        Invocation.getter(#court),
        returnValue: _FakeCourtModel_1(
          this,
          Invocation.getter(#court),
        ),
        returnValueForMissingStub: _FakeCourtModel_1(
          this,
          Invocation.getter(#court),
        ),
      ) as _i2.CourtModel);

  @override
  int get rainfallPercentage => (super.noSuchMethod(
        Invocation.getter(#rainfallPercentage),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
