// Mocks generated by Mockito 5.4.4 from annotations
// in court_booker_app/test/models/weather_model.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:court_booker_app/models/weather_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHourly_0 extends _i1.SmartFake implements _i2.Hourly {
  _FakeHourly_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherModel extends _i1.Mock implements _i2.WeatherModel {
  @override
  double get latitude => (super.noSuchMethod(
        Invocation.getter(#latitude),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get longitude => (super.noSuchMethod(
        Invocation.getter(#longitude),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get generationtimeMs => (super.noSuchMethod(
        Invocation.getter(#generationtimeMs),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get utcOffsetSeconds => (super.noSuchMethod(
        Invocation.getter(#utcOffsetSeconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get timezone => (super.noSuchMethod(
        Invocation.getter(#timezone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#timezone),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#timezone),
        ),
      ) as String);

  @override
  String get timezoneAbbreviation => (super.noSuchMethod(
        Invocation.getter(#timezoneAbbreviation),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#timezoneAbbreviation),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#timezoneAbbreviation),
        ),
      ) as String);

  @override
  _i2.Hourly get hourly => (super.noSuchMethod(
        Invocation.getter(#hourly),
        returnValue: _FakeHourly_0(
          this,
          Invocation.getter(#hourly),
        ),
        returnValueForMissingStub: _FakeHourly_0(
          this,
          Invocation.getter(#hourly),
        ),
      ) as _i2.Hourly);
}
